//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusRes.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class tblBu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblBu()
        {
            this.tblBookings = new HashSet<tblBooking>();
        }

        [DataMember]
        public string BusNo { get; set; }
        [DataMember]
        public int NoOfSeats { get; set; }
        [DataMember]
        public string Source_ { get; set; }
        [DataMember]
        public string Destination { get; set; }
        [DataMember]
        public string ViaStop { get; set; }
        [DataMember]
        public string StartTime { get; set; }
        [DataMember]
        public string EndTime { get; set; }
        [DataMember]
        public float PerSeatCost { get; set; }
        [DataMember]
        public bool BusType { get; set; }
        [DataMember]
        public string BusName { get; set; }
        [DataMember]
        public Nullable<int> Availableseats { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBooking> tblBookings { get; set; }
    }
}
